=== Kovomir/xml/zajezdy_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:kovj19:zajezdy"
    xmlns="urn:kovj19:zajezdy" elementFormDefault="qualified"
    xmlns:z="urn:kovj19:zajezdy">

    <xs:element name="zajezdy" type="zajezdyType">
        <xs:key name="prezdivkyInstruktoruKey">
            <xs:annotation>
                <xs:documentation>Klíč kontrolující unikátnost přezdívek instruktorů v seznamu instruktorů.</xs:documentation>
            </xs:annotation>
            <xs:selector xpath="z:instruktori/z:instruktor"/>
            <xs:field xpath="z:prezdivka"/>
        </xs:key>
        
        <xs:keyref refer="prezdivkyInstruktoruKey" name="instruktoriTurnusKey">
            <xs:annotation>
                <xs:documentation>Klíč pro kontrolu, jestli jsou na turnusech napsány jen ty přezdívky instruktorů,
                    které jsou v seznamu instruktorů.</xs:documentation>
            </xs:annotation>
            <xs:selector xpath="z:zajezd/z:turnus/z:instruktori/z:instruktor"/>
            <xs:field xpath="."/>
        </xs:keyref>
    </xs:element>

    <xs:complexType name="zajezdyType">
        <xs:sequence>
            <xs:element name="instruktori" type="instruktoriType"/>
            <xs:element name="zajezd" type="zajezdType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="instruktoriType">
        <xs:sequence>
            <xs:element name="instruktor" type="instruktorType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="instruktorType">
        <xs:sequence>
            <xs:element name="jmeno" type="neprazdnyRetezec"/>
            <xs:element name="prijmeni" type="neprazdnyRetezec"/>
            <xs:element name="prezdivka" type="neprazdnyRetezec"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="zajezdType">
        <xs:sequence>
            <xs:element name="nazev" type="xs:string"/>
            <xs:element name="zeme" type="xs:string"/>
            <xs:element name="fotky" type="fotkyType"/>
            <xs:element name="turnus" type="turnusType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="typ" type="typZajezduEnum" use="required"/>
    </xs:complexType>
    
    <xs:simpleType name="typZajezduEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="vodácký"/>
            <xs:enumeration value="turistický"/>
            <xs:enumeration value="lyžařský"/>
            <xs:enumeration value="horolezecký"/>
            <xs:enumeration value="ferratový"/>
            <xs:enumeration value="potápěčský"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="fotkyType">
        <xs:sequence>
            <xs:element name="fotka" type="fotkaType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fotkaType">
        <xs:sequence>
            <xs:element name="src" type="xs:string"/>
            <xs:element name="alt" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="turnusType">
        <xs:sequence>
            <xs:element name="instruktori" type="instruktoriZajezdType">
                <xs:key name="prezdivkyInstruktoruTurnusKey">
                    <xs:annotation>
                        <xs:documentation>Klíč kontrolující unikátnost přezdívek instruktorů na turnusu.</xs:documentation>
                    </xs:annotation>
                    <xs:selector xpath="z:instruktor"/>
                    <xs:field xpath="."/>
                </xs:key>
            </xs:element>
            <xs:element name="datumOdjezdu" type="xs:date"></xs:element>
            <xs:element name="datumPrijezdu" type="xs:date"></xs:element>
            <xs:element name="strava" type="stravaEnum"></xs:element>
            <xs:element name="doprava" type="dopravaEnum"></xs:element>
            <xs:element name="pocetMist" type="xs:int"></xs:element>
            <xs:element name="cena" type="cenaType"></xs:element>
            <xs:element name="ubytovani" type="ubytovaniType"></xs:element>
            <xs:element name="povinnaVybava" type="xs:string"></xs:element>
            <xs:element name="fyzickaNarocnost" type="narocnostEnum"></xs:element>
            <xs:element name="prihlaseni" type="prihlaseniType"></xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
    </xs:complexType>
    
    <xs:simpleType name="cenaType">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="narocnostEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="nízká"/>
            <xs:enumeration value="střední"/>
            <xs:enumeration value="vysoká"/>
            <xs:enumeration value="velmi vysoká"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="stravaEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="vlastní"/>
            <xs:enumeration value="zajištěna"/>
            <xs:enumeration value="polopenze"/>
            <xs:enumeration value="snídaně"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="dopravaEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="vlastní"/>
            <xs:enumeration value="minivan"/>
            <xs:enumeration value="autobus/vlak"/>
            <xs:enumeration value="letecká"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="instruktoriZajezdType">
        <xs:sequence>
            <xs:element name="instruktor" type="neprazdnyRetezec" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="ubytovaniType">
        <xs:sequence>
            <xs:element name="adresa" type="adresaType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="typ" type="typUbytovaniEnum" use="required"/>
    </xs:complexType>
    
    <xs:simpleType name="typUbytovaniEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="vlastní"/>
            <xs:enumeration value="stan"/>
            <xs:enumeration value="apartmán"/>
            <xs:enumeration value="hotel"/>
            <xs:enumeration value="kemp"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="adresaType">
        <xs:sequence>
            <xs:element name="ulice" type="neprazdnyRetezec"/>
            <xs:element name="mesto" type="neprazdnyRetezec"/>
            <xs:element name="psc" type="neprazdnyRetezec"/> <!-- PSČ v některých státech užívá i písmena (např. Nizozemsko) -->
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="prihlaseniType">
        <xs:sequence>
            <xs:element name="klient" type="klientType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="klientType">
        <xs:sequence>
            <xs:element name="jmeno" type="xs:string"/>
            <xs:element name="prijmeni" type="xs:string"/>
            <xs:element name="pohlavi" type="pohlaviEnum"/>
            <xs:element name="datumNarozeni" type="xs:date"></xs:element>
            <xs:element name="statniPrislusnost" type="xs:string"/>
            <xs:element name="email" type="emailType"/>
            <xs:element name="telefon" type="telefonType"/>
            <xs:element name="trvaleBydliste" type="adresaType"></xs:element>
            <xs:element name="zaplaceno" type="zaplacenoEnum"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="telefonType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\+?[0-9]*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="pohlaviEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Žena"/>
            <xs:enumeration value="Muž"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="zaplacenoEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ano"/>
            <xs:enumeration value="ne"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="neprazdnyRetezec">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Kovomir/xml/ukazkovy_dokument_final_v2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="zajezdy_schematron.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<zajezdy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:kovj19:zajezdy zajezdy_schema.xsd" xmlns="urn:kovj19:zajezdy"
    xmlns:z="urn:kovj19:zajezdy">
    <instruktori>
        <instruktor>
            <jmeno>Petr</jmeno>
            <prijmeni>Pavel</prijmeni>
            <prezdivka>Kosťa</prezdivka>
            <!-- slouží i jako Id zaměstnance, jde o malou firmu, každý má unikatní, kontrola referenční integrity, že v jednom turnusu se neopakují -->
        </instruktor>
        <instruktor>
            <jmeno>Jana</jmeno>
            <prijmeni>Dolecká</prijmeni>
            <prezdivka>Doly</prezdivka>
        </instruktor>
        <instruktor>
            <jmeno>Pavel</jmeno>
            <prijmeni>Uhlíř</prijmeni>
            <prezdivka>Pytel</prezdivka>
        </instruktor>
    </instruktori>
    <zajezd typ="ferratový">
        <nazev>Ferratový zájezd v Alpách</nazev>
        <zeme>Rakousko</zeme>
        <fotky>
            <fotka>
                <src>resources/rakousko.jpg</src>
                <alt>Ferrata Drachenwand</alt>
            </fotka>
        </fotky>
        <turnus id="981">
            <instruktori>
                <instruktor>Kosťa</instruktor>
            </instruktori>
            <datumOdjezdu>2021-05-13</datumOdjezdu>
            <datumPrijezdu>2021-05-19</datumPrijezdu>
            <strava>zajištěna</strava>
            <doprava>minivan</doprava>
            <pocetMist>7</pocetMist>
            <cena>8500</cena>
            <ubytovani typ="kemp">
                <adresa>
                    <ulice>Fusch an der Großglocknerstraße 5672</ulice>
                    <mesto>Gemeinde</mesto>
                    <psc>5061</psc>
                </adresa>
            </ubytovani>
            <povinnaVybava>ferratová brzda, přilba, pevné boty, sedák</povinnaVybava>
            <fyzickaNarocnost>vysoká</fyzickaNarocnost>
            <prihlaseni>
                <klient>
                    <jmeno>Jan</jmeno>
                    <prijmeni>Nový</prijmeni>
                    <pohlavi>Muž</pohlavi>
                    <datumNarozeni>1999-05-03</datumNarozeni>
                    <statniPrislusnost>Česká republika</statniPrislusnost>
                    <email>jan123@seznam.cz</email>
                    <telefon>+420870398478</telefon>
                    <trvaleBydliste>
                        <ulice>Dělnická 15</ulice>
                        <mesto>Praha 3</mesto>
                        <psc>12003</psc>
                    </trvaleBydliste>
                    <zaplaceno>ano</zaplaceno>
                </klient>
                <klient>
                    <jmeno>Pavla</jmeno>
                    <prijmeni>Nová</prijmeni>
                    <pohlavi>Žena</pohlavi>
                    <datumNarozeni>1988-06-26</datumNarozeni>
                    <statniPrislusnost>Česká republika</statniPrislusnost>
                    <email>pavla123@email.com</email>
                    <telefon>+420786670453</telefon>
                    <trvaleBydliste>
                        <ulice>Mostecká 13</ulice>
                        <mesto>Praha 6</mesto>
                        <psc>12018</psc>
                    </trvaleBydliste>
                    <zaplaceno>ano</zaplaceno>
                </klient>
                <klient>
                    <jmeno>Jakub</jmeno>
                    <prijmeni>Jungman</prijmeni>
                    <pohlavi>Muž</pohlavi>
                    <datumNarozeni>1990-11-03</datumNarozeni>
                    <statniPrislusnost>Česká republika</statniPrislusnost>
                    <email>jak.ju@email.cz</email>
                    <telefon>+420879657876</telefon>
                    <trvaleBydliste>
                        <ulice>Oslí 89</ulice>
                        <mesto>České Budějovice</mesto>
                        <psc>37005</psc>
                    </trvaleBydliste>
                    <zaplaceno>ano</zaplaceno>
                </klient>
            </prihlaseni>
        </turnus>
    </zajezd>
    <zajezd typ="turistický">
        <nazev>Hřebenovka Malé Fatry</nazev>
        <zeme>Slovensko</zeme>
        <fotky>
            <fotka>
                <src>resources/slovensko.jpg</src>
                <alt>Hřebenovka Malé Fatry</alt>
            </fotka>
        </fotky>
        <turnus id="982">
            <instruktori>
                <instruktor>Doly</instruktor>
            </instruktori>
            <datumOdjezdu>2021-06-01</datumOdjezdu>
            <datumPrijezdu>2021-06-05</datumPrijezdu>
            <strava>vlastní</strava>
            <doprava>minivan</doprava>
            <pocetMist>7</pocetMist>
            <cena>4000</cena>
            <ubytovani typ="stan"/>
            <povinnaVybava>turistická obuv, krosna</povinnaVybava>
            <fyzickaNarocnost>nízká</fyzickaNarocnost>
            <prihlaseni>
                <klient>
                    <jmeno>Jakub</jmeno>
                    <prijmeni>Dorbert</prijmeni>
                    <pohlavi>Muž</pohlavi>
                    <datumNarozeni>1997-03-11</datumNarozeni>
                    <statniPrislusnost>Česká republika</statniPrislusnost>
                    <email>jak902@seznam.cz</email>
                    <telefon>+420829876478</telefon>
                    <trvaleBydliste>
                        <ulice>Prokopova 13</ulice>
                        <mesto>Mšeno</mesto>
                        <psc>12023</psc>
                    </trvaleBydliste>
                    <zaplaceno>ano</zaplaceno>
                </klient>
            </prihlaseni>
        </turnus>
        <turnus id="983">
            <instruktori>
                <instruktor>Doly</instruktor>
            </instruktori>
            <datumOdjezdu>2021-07-01</datumOdjezdu>
            <datumPrijezdu>2021-07-05</datumPrijezdu>
            <strava>vlastní</strava>
            <doprava>minivan</doprava>
            <pocetMist>7</pocetMist>
            <cena>4000</cena>
            <ubytovani typ="stan"/>
            <povinnaVybava>turistická obuv, krosna</povinnaVybava>
            <fyzickaNarocnost>nízká</fyzickaNarocnost>
            <prihlaseni/>
        </turnus>
    </zajezd>
    <zajezd typ="vodácký">
        <nazev>Rafting na Soči</nazev>
        <zeme>Slovinsko</zeme>
        <fotky>
            <fotka>
                <src>resources/slovinsko.jpg</src>
                <alt>Rafting na řece Soči</alt>
            </fotka>
        </fotky>
        <turnus id="1003">
            <instruktori>
                <instruktor>Pytel</instruktor>
                <instruktor>Doly</instruktor>
            </instruktori>
            <datumOdjezdu>2021-06-19</datumOdjezdu>
            <datumPrijezdu>2021-06-26</datumPrijezdu>
            <strava>zajištěna</strava>
            <doprava>vlastní</doprava>
            <pocetMist>15</pocetMist>
            <cena>9999</cena>
            <ubytovani typ="apartmán">
                <adresa>
                    <ulice>Lepena 2</ulice>
                    <mesto>Soča</mesto>
                    <psc>5232</psc>
                </adresa>
            </ubytovani>
            <povinnaVybava>boty do vody, neopren</povinnaVybava>
            <fyzickaNarocnost>nízká</fyzickaNarocnost>
            <prihlaseni>
                <klient>
                    <jmeno>Jakub</jmeno>
                    <prijmeni>Petr</prijmeni>
                    <pohlavi>Muž</pohlavi>
                    <datumNarozeni>1992-11-11</datumNarozeni>
                    <statniPrislusnost>Česká republika</statniPrislusnost>
                    <email>jape93@seznam.cz</email>
                    <telefon>+420234876478</telefon>
                    <trvaleBydliste>
                        <ulice>Luční 3</ulice>
                        <mesto>Most</mesto>
                        <psc>34923</psc>
                    </trvaleBydliste>
                    <zaplaceno>ano</zaplaceno>
                </klient>
                <klient>
                    <jmeno>Pavla</jmeno>
                    <prijmeni>Petrová</prijmeni>
                    <pohlavi>Žena</pohlavi>
                    <datumNarozeni>1992-03-11</datumNarozeni>
                    <statniPrislusnost>Česká republika</statniPrislusnost>
                    <email>pape94@seznam.cz</email>
                    <telefon>+420987876478</telefon>
                    <trvaleBydliste>
                        <ulice>Luční 3</ulice>
                        <mesto>Most</mesto>
                        <psc>34923</psc>
                    </trvaleBydliste>
                    <zaplaceno>ano</zaplaceno>
                </klient>
            </prihlaseni>
        </turnus>
    </zajezd>
</zajezdy>
